import os
# from langchain.memory import ConversationBufferMemory

# app constants

app_title = "✨ BIDA"
app_version = "v0.5"
manual_version = "2026"
copyright = "\u00A9 TEOCO, 2026"
app_long_name = "BIllTrak Digital Assistant"
footer_text = "Disclaimer: This is a prototype application and the responses are generated by an AI model."

settings_json_file_name = "./settings.json"
book_open_close_gif = 'book-82-3.gif'
book_open_close_gif_path = './app/static/icons/animation/' + book_open_close_gif
book_open_close_small_gif = 'book-82-4.gif'
book_open_close_small_gif_path = './app/static/icons/animation/' + book_open_close_small_gif
teoco_logo = './app/static/icons/teoco.png'
main_page_image_path = "./app/static/icons/landing_page_BIDA.png"

# Directories
QA_DIR = 'QA'
SVG_DIR = 'static/icons/animation/'
# File

# Flags
PRINT_MESSAGES = True

# Query Vectorestore
num_docs_returned_by_chain = 10           # per-method top-k (wider pool for reranker)
num_docs_fetch_and_feed_to_llm = 10
bm25_top_k = 10
image_score_threshold = 0.3
rerank_top_k = 8                          # final count fed to LLM after rerank
reranker_model_name = "cross-encoder/ms-marco-MiniLM-L-12-v2"

# Show first characters of the chat question in the histroy button
HISTORY_BUTTON_CHAR_LIMIT = 50
EXTRACT_N_CHARS_FROM_PROMPT = 100

# define memory
# memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ['STREAMLIT_SERVER_ENABLE_STATIC_SERVING'] = 'true'

ACRONYM_CSV = 'BIDA-Acronyms.csv'

FONT_FAMILIES = ["Arial", "Helvetica", "Times New Roman", "Courier New", \
    "Verdana", "Georgia", "Segoe UI", "Trebuchet MS", "Impact", "Comic Sans MS", \
    "Lucida Console", "Consolas", "Monaco"]

# Color customization — element labels, session-state keys, and defaults
COLOR_ELEMENT_LABELS = [
    "Main Area",
    "Sidebar",
    "Text Color",
    "Question Text Box",
    "Question Background",
    "Answer Background",
    "Preceding Context",
    "Following Context",
    "Expander Color",
    "User Name Background",
    "Button Color",
    "Button Label Color",
    "Button Hover",
]

COLOR_LABEL_TO_KEY = {
    "Main Area": "__main_area_color",
    "Sidebar": "__sidebar_color",
    "Text Color": "__text_color",
    "Question Text Box": "__question_textbox_color",
    "Question Background": "__question_bg_color",
    "Answer Background": "__answer_bg_color",
    "Preceding Context": "__preceding_bg_color",
    "Following Context": "__following_bg_color",
    "Expander Color": "__expander_color",
    "User Name Background": "__username_bg_color",
    "Button Color": "__button_color",
    "Button Label Color": "__button_label_color",
    "Button Hover": "__button_hover_color",
}

COLOR_DARK_DEFAULTS = {
    "__main_area_color": "#0e1117",
    "__sidebar_color": "#262730",
    "__text_color": "#F5F5F5",
    "__question_textbox_color": "#262730",
    "__question_bg_color": "#475063",
    "__answer_bg_color": "#2b313e",
    "__preceding_bg_color": "#1a3a5c",
    "__following_bg_color": "#3a2a1c",
    "__expander_color": "#262730",
    "__username_bg_color": "#1a1a2e",
    "__button_color": "#262730",
    "__button_label_color": "#F5F5F5",
    "__button_hover_color": "#8B1F2B",
}

COLOR_LIGHT_DEFAULTS = {
    "__main_area_color": "#FFFFFF",
    "__sidebar_color": "#F0F2F6",
    "__text_color": "#1A1A2E",
    "__question_textbox_color": "#FFFFFF",
    "__question_bg_color": "#E8EEF7",
    "__answer_bg_color": "#F5F7FA",
    "__preceding_bg_color": "#D6EAF8",
    "__following_bg_color": "#FAE5D3",
    "__expander_color": "#DFE2E2",
    "__username_bg_color": "#DCE1E7",
    "__button_color": "#FFFFFF",
    "__button_label_color": "#1A1A2E",
    "__button_hover_color": "#8B1F2B",
}

COLOR_ELEMENT_DEFAULTS = COLOR_DARK_DEFAULTS
ANIMATION_CATEGORY = ["Pencil", "Latex", "Table", "Image"]
ANIMATION_STYLE = ['none', 'blink', 'flash', 'rotate', 'scale', 'fadeIn', 'slide', 'pulse']

table_text_color = 'inherit'
table_outline_color = 'rgba(96, 96, 96, 0.55)'
header_bg_color = 'rgba(96, 96, 96, 0.55)'
header_text_color = 'inherit'
row_zebra_color = 'rgba(96, 96, 96, 0.3)'
text_align = 'left'
padding = '8px 10px'

# Color used by all the blinking streaming-indicator icons
# (pencil / image / lambda / book_open). Change this one constant to
# retheme every flashing icon.
blinking_icon_color = '#8B1F2B'

custom_container_red = 18
custom_container_green = 52
custom_container_blue = 86
custom_container_alpha = 0.5

# set of strings we want to check in the response
# If found, skip displaying document chunks
strings_to_check_in_response = {
    "I don't know",
    "I'm not sure",
    "I'm sorry",
    "I don't understand",
    "How can I help you",
    "Hello",
    "AI language model",
    "Failed to get response after multiple retries.",
    "I'm BIDA",
    "I am BIDA",
    # Off-topic refusal — produced when the user asks about something
    # outside BillTrak (weather, news, etc.). Sources are irrelevant in
    # that case, so suppress Text Sources / Related Screenshots.
    "I can only answer questions about BillTrak",
}

greetings = {
    "Who are you?": "I am BIDA, a digital assistant for TEOCO. How may I assist you?",
    "Hello": "Greetings! How may I assist you?",
    "Hi": "Good day! How can I help you?",
    "Hey": "Hello! How may I be of service?",
    "Good morning": "Good morning! I hope you have a splendid day.",
    "Good afternoon": "Good afternoon! How may I assist you?",
    "Good evening": "Good evening! Is there anything I can help you with?",
    "Howdy": "Greetings! What brings you here?",
    "Greetings": "Greetings! How may I assist you today?",
    "Yo": "Greetings! What's going on?",
    "What's up": "Hello! Not much, just here to assist.",
    "Nice to meet you": "Pleasure to meet you! How may I assist you?",
    "How are you?": "I am well, thank you. How about yourself?",
    "Long time no see": "Indeed! It has been a while. What's new?",
    "How's it going?": "Things are going well! How about for you?",
    "Hey there, stranger": "Hello! Long time no talk. What's up?",
    "Hiya": "Greetings! How may I brighten your day?",
    "Bonjour": "Bonjour! Comment ça va?",
    "Hola": "¡Hola! ¿Cómo está usted?",
    "Ciao": "Ciao! Come sta?",
    "Namaste": "Namaste! How may I assist you today?",
    "Salutations": "Salutations! What can I do for you?",
    "Wassup": "Greetings! What's happening?",
    "Hey you!": "Hello! What's going on with you?",
    "Hey stranger": "Hello! Long time no see. What's new?",
    "Hi friend": "Greetings, friend! How may I help you?",
    "Good to see you": "It's a pleasure to see you! What brings you here?",
    "How's your day?": "It's going well, thanks! How about yours?",
    "Hey sunshine": "Hello! You're my sunshine today. What's up?",
    "Hi there!": "Hello there! How's everything on your end?",
    "Top of the morning to you": "Top of the morning! What's on your agenda?",
    "Hey bud": "Greetings! What's going on?",
    "How's everything?": "Everything is good! How about for you?",
    "Hi stranger": "Hello! Long time no talk. What's going on?",
    "Hey you": "Hello! What's up?",
    "Hi mate": "Greetings! How may I assist you today?",
    "Greetings and salutations": "Greetings and salutations! What can I do for you?",
    "Hello, friend": "Hello, friend! How may I brighten your day?",
    "Good day": "Good day! What brings you here?",
    "Hey buddy": "Greetings! How may I help you?",
    "What's happening?": "Hello! What's happening with you?",
    "Hiya, pal": "Greetings, pal! How may I assist you today?",
    "Hello there": "Hello there! How may I make your day better?",
    "Hey amigo": "Greetings, amigo! ¿Cómo está usted?",
    "How's life treating you?": "Life is treating me well! How about you?",
    "Hey chief": "Greetings, chief! What's on your mind?",
    "Hiya, friend": "Greetings, friend! How may I assist you today?",
    "Hey partner": "Greetings, partner! What's going on?",
    "Greetings, Earthling": "Greetings, Earthling! How may I help you?",
    "Sup": "Not much, just chilling. How about you?",
    "Hey there": "Hello there! What's going on?",
    "How's your day going?": "It's going well! How about yours?",
    "Hi stranger, long time no talk": "Hello! Yes, it's been a while. What's new?",
    "How's the world treating you?": "The world is treating me well! How about you?",
    "Hi partner in crime": "Hello there! Ready for some mischief?",
    "Hey you, what's the buzz?": "Greetings! Not much, just here. What's the buzz with you?",
    "What's the good word?": "Hello! What's the good word on your end?",
    "Greetings, comrade": "Greetings, comrade! How may I assist you today?",
    "Hiya, neighbor": "Greetings, neighbor! What brings you by?",
    "Hey amigo, long time no see": "Greetings, amigo! It's been too long. What's up?",
    "Hey champ": "Greetings, champ! What's going on?",
    "How goes it?": "Things are going well! How about your side of things?",
    "Hiya, sport": "Greetings, sport! What's the game plan?",
    "Hey rockstar": "Greetings, rockstar! Ready to conquer the day?",
    "What's cracking?": "Hello! What's cracking on your end?",
    "Hiya, chief": "Greetings, chief! How may I assist you today?",
    "Hey genius": "Greetings, genius! What's on your brilliant mind?",
    "What's the 411?": "Hello! What's the 411 with you?",
    "Hey superhero": "Greetings, superhero! Ready to save the day?",
    "Howdy-do": "Greetings! What's on your agenda?",
    "Hiya, captain": "Greetings, captain! What's the mission for today?",
    "Hey trendsetter": "Greetings, trendsetter! What's the latest trend?",
    "Greetings, fellow human": "Greetings, fellow human! How may I help you?",
    "Hey dynamo": "Greetings, dynamo! What's energizing you today?",
    "How's tricks?": "Tricks are good! How about you?",
    "Hiya, maestro": "Greetings, maestro! What's the symphony of your day?",
    "Hey whiz": "Greetings, whiz! What's your latest brilliant idea?",
    "How's the ball rolling?": "The ball is rolling smoothly! How about yours?",
    "Hiya, guru": "Greetings, guru! What wisdom do you bring today?",
    "Hey navigator": "Greetings, navigator! What's the course for today?",
    "How's the journey?": "The journey is good! How about yours?",
    "Hi there, trendsetter": "Hello there, trendsetter! What's the latest in style?",
    "Hey sparkplug": "Greetings, sparkplug! What's igniting your day?",
    "What's shaking?": "Hello! What's shaking on your side?",
    "Hiya, visionary": "Greetings, visionary! What's your vision for today?",
    "Hey conductor": "Greetings, conductor! What's the melody of your day?",
    "How's the groove?": "The groove is good! How about yours?",
    "Hi there, navigator": "Hello there, navigator! What's the course for today?",
    "Hey maestro": "Greetings, maestro! What's the symphony of your day?",
    "What's the scoop?": "Hello! What's the scoop on your side?",
    "Hiya, wizard": "Greetings, wizard! What magical things are you up to?",
    "Hey commander": "Greetings, commander! What's the mission for today?",
    "How's the expedition?": "The expedition is going well! How about yours?",
}